### ISSUE TITLE
In LevelProgressionDef LevelXPTable[N] array dont work

### ISSUE THREAD

**Issue by Aluvarka** [tracktwo/ppdefmodifier#1]
Hello, thank you for PPDefModifier and adding array support. Sadly but changes for LevelProgressionDef seem's don't work, i try different aproaches but only below didn't show me error msg in PPModLoader.log and still dont change anything in game. Is i do something wrong?

```json
	{
		"guid": "ffd0b060-d778-0504-39fd-4269dee2a199",
		"field": "LevelXPTable[1].ExperienceRequirement",
		"value": 200,
		"comment": "LevelProgressionDef 1 lvl exp"
	}

**Comment by tracktwo** [comment]
Thanks, confirmed that this one doesn't work. It's not the array index itself, but something to do with how the XP table is represented in the game. It looks like the mod is getting a copy of the table and modifying that one, instead of modifying the original table in-place. It may be something to do with the fact that the LevelXPTable's type is a nested class. The array syntax does work for DamagePayload in weapon defs.

I'll need to do some more digging to figure out what the difference is and how to make sure I can modify the original in-place.

**Comment by tracktwo** [comment]
Ok, I figured out what's going on with this one. It doesn't work because LevelData is declared as a struct, not a class. I am not terribly familiar with C#, but from what i can gather from a little bit of googling around is that the reflection mechanisms I use for pulling out and modifying these things don't really work with value types and there is no way to get a reference to these things from these APIs. 

Maybe there is some way to do it, but I'm not sure yet what it is. In theory these value types can be copied back into their containing objects but I'm not exactly sure how to keep track of all the pieces yet.

**Comment by tracktwo** [comment]
Copying the new changes back into the parents works. Please try version 1.2, the snippet you have above should work now.
